default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: exchange_rate_provider_development

test:
  <<: *default
  database: exchange_rate_provider_test

production:
  <<: *default
  database: exchange_rate_provider_production
  username: exchange_rate_provider
  password: <%= ENV["EXCHANGE_RATE_PROVIDER_DATABASE_PASSWORD"] %>
